#!/bin/sh
set -e
	
not_enabled_warning() {
	echo "usrkeeper warning: usrkeeper is not yet enabled for $(pwd)" >&2
	echo "usrkeeper warning: run usrkeeper init to enable it" >&2
}

if [ "$VCS" = git ] && [ ! -d .git ]; then
	not_enabled_warning
elif [ "$VCS" = hg ] && [ ! -d .hg ]; then
	not_enabled_warning
elif [ "$VCS" = bzr ] && [ ! -d .bzr ]; then
	not_enabled_warning
elif [ "$VCS" = darcs ] && [ ! -d _darcs ]; then
	not_enabled_warning
fi
