#!/bin/sh
set -e

pl="/var/cache/usrkeeper/packagelist"

if usrkeeper unclean; then
	message="committing changes in /etc after $HIGHLEVEL_PACKAGE_MANAGER run"

	set +e
	if [ -e $pl.pre-install ] && [ "$(cat $pl.fmt 2>/dev/null || true)" = "$(usrkeeper list-installed fmt)" ]; then
		(
			echo "$message"
			echo
			echo "Package changes:"
			usrkeeper list-installed | diff -U0 $pl.pre-install - | tail -n+4 | egrep '^[-+]' || true
		) | usrkeeper commit --stdin
	else
		usrkeeper commit "$(printf "$message")"
	fi
	status=$?
	set -e

	if [ "$status" != 0 ]; then
		echo "warning: usrkeeper failed to commit changes in /etc using $VCS" >&2
	fi
fi
	
rm -f $pl.pre-install $pl.fmt
