#!/bin/sh
set -e

if [ "$1" = purge ]; then
	if [ -e /etc/.usrkeeper ]; then
		. /usr/share/debconf/confmodule
	
		# uninit on purge is tricky because usrkeeper's configuration
		# and code has been removed at this point. This relies on a
		# stashed away copy.
		if [ -e /var/cache/usrkeeper/stash/usrkeeper.conf ] &&
		   [ -d /var/cache/usrkeeper/stash/uninit.d ] &&
		   [ -x /var/cache/usrkeeper/stash/usrkeeper ]; then
			. /var/cache/usrkeeper/stash/usrkeeper.conf
			if [ -n "$VCS" ]; then
				db_subst usrkeeper/purge VCS "$VCS"
				db_input critical usrkeeper/purge || true
				db_go || true
				db_get usrkeeper/purge
				if [ "$RET" = true ]; then
					USRKEEPER_CONF_DIR=/var/cache/usrkeeper/stash
					export USRKEEPER_CONF_DIR
					/var/cache/usrkeeper/stash/usrkeeper uninit -f || true
				fi
			fi
		fi
	fi
	rm -rf /var/cache/usrkeeper
fi

#DEBHELPER#
