#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = remove ]; then
	# In case usrkeeper is being purged, stash away a copy of
	# the files purging will need.
	mkdir -p /var/cache/usrkeeper/stash
	if [ -e /etc/usrkeeper/usrkeeper.conf ]; then
		cp -a /etc/usrkeeper/usrkeeper.conf /var/cache/usrkeeper/stash
	fi
	if [ -d /etc/usrkeeper/uninit.d ]; then
		cp -a /etc/usrkeeper/uninit.d /var/cache/usrkeeper/stash
	fi
	if [ -x /usr/bin/usrkeeper ]; then
		cp -a /usr/bin/usrkeeper /var/cache/usrkeeper/stash
	fi
fi
