#!/bin/sh
# This list will be later used when committing.
mkdir -p /var/cache/usrkeeper/
usrkeeper list-installed > /var/cache/usrkeeper/packagelist.pre-install
usrkeeper list-installed fmt > /var/cache/usrkeeper/packagelist.fmt
